//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hackathonDB : DbContext
    {
        public hackathonDB()
            : base("name=hackathonDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<recipe_0_orders_details> recipe_0_orders_details { get; set; }
        public virtual DbSet<recipe_0_out_semi_finished_production> recipe_0_out_semi_finished_production { get; set; }
        public virtual DbSet<recipe_0_out_test_during_production> recipe_0_out_test_during_production { get; set; }
        public virtual DbSet<recipe_0_processing_details_bigbag> recipe_0_processing_details_bigbag { get; set; }
        public virtual DbSet<recipe_0_processing_details_dd> recipe_0_processing_details_dd { get; set; }
        public virtual DbSet<recipe_0_processing_details_slurry> recipe_0_processing_details_slurry { get; set; }
        public virtual DbSet<recipe_0_raw_material_in> recipe_0_raw_material_in { get; set; }
        public virtual DbSet<recipe_0_raw_material_used> recipe_0_raw_material_used { get; set; }
        public virtual DbSet<recipe_1_orders_details> recipe_1_orders_details { get; set; }
        public virtual DbSet<recipe_1_out_semi_finished_production> recipe_1_out_semi_finished_production { get; set; }
        public virtual DbSet<recipe_1_out_test_during_production> recipe_1_out_test_during_production { get; set; }
        public virtual DbSet<recipe_1_processing_details_bigbag> recipe_1_processing_details_bigbag { get; set; }
        public virtual DbSet<recipe_1_processing_details_dd> recipe_1_processing_details_dd { get; set; }
        public virtual DbSet<recipe_1_processing_details_slurry> recipe_1_processing_details_slurry { get; set; }
        public virtual DbSet<recipe_1_raw_material_in> recipe_1_raw_material_in { get; set; }
        public virtual DbSet<recipe_1_raw_material_used> recipe_1_raw_material_used { get; set; }
        public virtual DbSet<results_test_dataset> results_test_dataset { get; set; }
    }
}
