//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe_1_processing_details_slurry
    {
        public int orders_details_id { get; set; }
        public int slurry_process_order { get; set; }
        public string slurry_line { get; set; }
        public Nullable<System.DateTime> slurry_start_time { get; set; }
        public Nullable<double> water_pct { get; set; }
        public Nullable<double> water_correction { get; set; }
    
        public virtual recipe_1_orders_details recipe_1_orders_details { get; set; }
    }
}
