//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe_0_raw_material_in
    {
        public int id { get; set; }
        public int process_order_sap3 { get; set; }
        public Nullable<double> fat_pct { get; set; }
        public Nullable<double> particles_grp1 { get; set; }
        public Nullable<double> particles_grp2 { get; set; }
        public Nullable<double> particles_grp3 { get; set; }
        public Nullable<double> moisture { get; set; }
    
        public virtual recipe_0_orders_details recipe_0_orders_details { get; set; }
    }
}
