//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe_0_orders_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipe_0_orders_details()
        {
            this.recipe_0_out_semi_finished_production = new HashSet<recipe_0_out_semi_finished_production>();
            this.recipe_0_out_test_during_production = new HashSet<recipe_0_out_test_during_production>();
            this.recipe_0_processing_details_bigbag = new HashSet<recipe_0_processing_details_bigbag>();
            this.recipe_0_processing_details_dd = new HashSet<recipe_0_processing_details_dd>();
            this.recipe_0_processing_details_slurry = new HashSet<recipe_0_processing_details_slurry>();
            this.recipe_0_raw_material_used = new HashSet<recipe_0_raw_material_used>();
            this.recipe_0_raw_material_in = new HashSet<recipe_0_raw_material_in>();
        }
    
        public int id { get; set; }
        public string line_dd { get; set; }
        public Nullable<long> production_order { get; set; }
        public Nullable<long> process_order_sap { get; set; }
        public Nullable<long> material_code { get; set; }
        public Nullable<long> recipe { get; set; }
        public Nullable<System.DateTime> activation_date { get; set; }
        public Nullable<System.DateTime> closing_date { get; set; }
        public string data_split { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_0_out_semi_finished_production> recipe_0_out_semi_finished_production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_0_out_test_during_production> recipe_0_out_test_during_production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_0_processing_details_bigbag> recipe_0_processing_details_bigbag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_0_processing_details_dd> recipe_0_processing_details_dd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_0_processing_details_slurry> recipe_0_processing_details_slurry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_0_raw_material_used> recipe_0_raw_material_used { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipe_0_raw_material_in> recipe_0_raw_material_in { get; set; }
    }
}
